### ISSUE TITLE
Send as MediaStream the canvasCtx.captureStream(FrameRate)

### ISSUE THREAD

**Issue by jimver04** [open-easyrtc/open-easyrtc#73]
Instead of video stream can I send the captured canvas ?

```
const canvas = document.getElementById('my-vfx-video-canvas');
const ctx = canvas.getContext('2d');
var newVideoStream = ctx.captureStream(30); 
```

where 30 is the frame rate for capturing the canvas.
My canvas has also transparent pixels, will they be transferred as transparent ? In which line should I set it ?
Can you support it in the next version ?

Best,
Dimitrios Ververidis @ MediaVerse project

**Comment by hthetiot** [comment]
See my reply here https://github.com/networked-aframe/networked-aframe/issues/269#issuecomment-916065095 

This is not at all an open-easyrtc issue just a network-aframe api limitations and integration.
Not sure what "test" you did to make you conclusion.

**Comment by hthetiot** [comment]
> My canvas has also transparent pixels, will they be transferred as transparent ?

No captureStream will render black on transparent canvas that how video works transparent video does not exist and the fact you even think it's possible made me laugh.

**Comment by vincentfretin** [comment]
I did some search, transparent webm videos exists, more like a hack to the VP8/VP9 codec and is implemented in Firefox and Chrome, see https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video
But there may be limitations to `canvas.captureStream`, `MediaRecorder`, and `RTCPeerConnection` API. Even if you manage to create a transparent video from the canvas, you will apparently lose the alpha channel when transferring the stream via WebRTC, so the other participants will indeed see black background instead of transparent. Here are interesting links I found on the subject:
- https://bugs.chromium.org/p/chromium/issues/detail?id=690968
- https://stackoverflow.com/questions/42146396/capture-video-with-alpha-channel-using-canvas-capturestream
- https://groups.google.com/g/discuss-webrtc/c/abe2lVcjVtE
- https://github.com/w3c/mediacapture-fromelement/issues/30#issuecomment-747553647

**Comment by hthetiot** [comment]
Personally I don't use VP8 o VP9 for WebRTC, H265 and H264 are much better.

**Comment by jimver04** [comment]
I know that alpha channel passes as black through WebRTC. This guy from Google (samdutton) has did what I want for another WebRTC implementation (WebRTC implementations everywhere)

https://webrtc.github.io/samples/src/content/capture/canvas-pc/

My future steps are
1) transfer this example to work with Open-EasyRTC

2) Then, draw green pixels on the video background (found with Mediapipe before sending the data) on the client that sends data and then make a custom shader in Three.js for the plane that receives the video texture to remove green pixels (at client side).

**Comment by hthetiot** [comment]
This example only capture canvas and pass it as a stream, nothing that cannot be done today with open-easyrtc, it does not make anything regarding transparent video. Removing green pixel is not the same as transparency and will most likely left green artefacts and what if i where a green shirt? 
In any case that have nothing to do with open easyrtc scope and we already support canvas capture out of the box so this issue is closed since their is nothing to be added and i don't have time to easte with people that create a issue with a title for a feature that can already be achieved out of the box and then add that they want to do stuff that are out of the scope anyway of this library.
